version: '3.8'

volumes:
  db-data:
    driver: local

services:
  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messageSender_v1_service
    depends_on:
      - db_postgres_15
    env_file:
      - .env
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - SPRING_DATASOURCE_URL = jdbc:postgresql://db_postgres_15/messageSender
      - MAIL_HOST = ${MAIL_HOST}
      - MAIL_PORT = ${MAIL_PORT}
      - MAIL_SENDER = ${MAIL_SENDER}
      - MAIL_PASSWORD = ${MAIL_PASSWORD}
      - MAIL_PROTOCOL = ${MAIL_PROTOCOL}
      - MAIL_AUTH = ${MAIL_AUTH}
      - MAIL_STARTTLS_ENABLE = ${MAIL_STARTTLS_ENABLE}
      - EMAIL_DEBUG = ${EMAIL_DEBUG}
    ports:
      - "8181:8181"

  db_postgres_15:
    image: postgres:15
    container_name: db_postgres
    environment:
      POSTGRES_DB: messageSender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - db-data:/var/lib/postgresql/data