server:
  port: 8181
spring:
  config:
    application:
      name: MessageSender
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false